var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/onboarding/step-5/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0aqfpht._.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0jp_0gl.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0japkqw._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.angw.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/[root-of-the-server]__05bxrjl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_onboarding_layout_tsx_0fkh9mc._.js")
R.c("server/chunks/ssr/_next-internal_server_app_onboarding_step-5_page_actions_0itrq98.js")
R.m(19649)
module.exports=R.m(19649).exports
