// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/step-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/step-1">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/step-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/step-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/step-2">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/step-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/step-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/step-3">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/step-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/step-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/step-4">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/step-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/step-5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/step-5">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/step-5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/step-6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/step-6">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/step-6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/step-7/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/step-7">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/step-7/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ops/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops/audit">> = Specific
  const handler = {} as typeof import("../../src/app/ops/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ops/deals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops/deals/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/ops/deals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ops/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops/deals">> = Specific
  const handler = {} as typeof import("../../src/app/ops/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ops/escalations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops/escalations">> = Specific
  const handler = {} as typeof import("../../src/app/ops/escalations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops">> = Specific
  const handler = {} as typeof import("../../src/app/ops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/deals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/deals/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/portal/deals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/deals">> = Specific
  const handler = {} as typeof import("../../src/app/portal/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../src/app/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/resend-magic-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resend-magic-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/resend-magic-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/process-jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/process-jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/process-jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/create-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/create-checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/create-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/intake">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/resend/inbound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/resend/inbound">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/resend/inbound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ops/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ops">> = Specific
  const handler = {} as typeof import("../../src/app/ops/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../src/app/portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
