var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/resend-magic-link/route.js")
R.c("server/chunks/[root-of-the-server]__05xa970._.js")
R.c("server/chunks/node_modules_0f_9_~i._.js")
R.c("server/chunks/[root-of-the-server]__120-c~1._.js")
R.c("server/chunks/_0eog.z_._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_072isxd._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_resend-magic-link_route_actions_0nb7-zr.js")
R.m(60478)
module.exports=R.m(60478).exports
